/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as IntervencaoRouteImport } from './routes/intervencao'
import { Route as IntegracaoRouteImport } from './routes/integracao'
import { Route as EscolaRouteImport } from './routes/escola'
import { Route as EntidadesRouteImport } from './routes/entidades'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurmaIdRouteImport } from './routes/turma.$id'
import { Route as AlunoIdRouteImport } from './routes/aluno.$id'
import { Route as AuthenticatedCortexRouteImport } from './routes/_authenticated/cortex'

const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntervencaoRoute = IntervencaoRouteImport.update({
  id: '/intervencao',
  path: '/intervencao',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoRoute = IntegracaoRouteImport.update({
  id: '/integracao',
  path: '/integracao',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolaRoute = EscolaRouteImport.update({
  id: '/escola',
  path: '/escola',
  getParentRoute: () => rootRouteImport,
} as any)
const EntidadesRoute = EntidadesRouteImport.update({
  id: '/entidades',
  path: '/entidades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmaIdRoute = TurmaIdRouteImport.update({
  id: '/turma/$id',
  path: '/turma/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIdRoute = AlunoIdRouteImport.update({
  id: '/aluno/$id',
  path: '/aluno/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCortexRoute = AuthenticatedCortexRouteImport.update({
  id: '/cortex',
  path: '/cortex',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/auth': typeof AuthRoute
  '/entidades': typeof EntidadesRoute
  '/escola': typeof EscolaRoute
  '/integracao': typeof IntegracaoRoute
  '/intervencao': typeof IntervencaoRoute
  '/turmas': typeof TurmasRoute
  '/cortex': typeof AuthenticatedCortexRoute
  '/aluno/$id': typeof AlunoIdRoute
  '/turma/$id': typeof TurmaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/auth': typeof AuthRoute
  '/entidades': typeof EntidadesRoute
  '/escola': typeof EscolaRoute
  '/integracao': typeof IntegracaoRoute
  '/intervencao': typeof IntervencaoRoute
  '/turmas': typeof TurmasRoute
  '/cortex': typeof AuthenticatedCortexRoute
  '/aluno/$id': typeof AlunoIdRoute
  '/turma/$id': typeof TurmaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alunos': typeof AlunosRoute
  '/auth': typeof AuthRoute
  '/entidades': typeof EntidadesRoute
  '/escola': typeof EscolaRoute
  '/integracao': typeof IntegracaoRoute
  '/intervencao': typeof IntervencaoRoute
  '/turmas': typeof TurmasRoute
  '/_authenticated/cortex': typeof AuthenticatedCortexRoute
  '/aluno/$id': typeof AlunoIdRoute
  '/turma/$id': typeof TurmaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/auth'
    | '/entidades'
    | '/escola'
    | '/integracao'
    | '/intervencao'
    | '/turmas'
    | '/cortex'
    | '/aluno/$id'
    | '/turma/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/auth'
    | '/entidades'
    | '/escola'
    | '/integracao'
    | '/intervencao'
    | '/turmas'
    | '/cortex'
    | '/aluno/$id'
    | '/turma/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alunos'
    | '/auth'
    | '/entidades'
    | '/escola'
    | '/integracao'
    | '/intervencao'
    | '/turmas'
    | '/_authenticated/cortex'
    | '/aluno/$id'
    | '/turma/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlunosRoute: typeof AlunosRoute
  AuthRoute: typeof AuthRoute
  EntidadesRoute: typeof EntidadesRoute
  EscolaRoute: typeof EscolaRoute
  IntegracaoRoute: typeof IntegracaoRoute
  IntervencaoRoute: typeof IntervencaoRoute
  TurmasRoute: typeof TurmasRoute
  AlunoIdRoute: typeof AlunoIdRoute
  TurmaIdRoute: typeof TurmaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervencao': {
      id: '/intervencao'
      path: '/intervencao'
      fullPath: '/intervencao'
      preLoaderRoute: typeof IntervencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao': {
      id: '/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof IntegracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola': {
      id: '/escola'
      path: '/escola'
      fullPath: '/escola'
      preLoaderRoute: typeof EscolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entidades': {
      id: '/entidades'
      path: '/entidades'
      fullPath: '/entidades'
      preLoaderRoute: typeof EntidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turma/$id': {
      id: '/turma/$id'
      path: '/turma/$id'
      fullPath: '/turma/$id'
      preLoaderRoute: typeof TurmaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/$id': {
      id: '/aluno/$id'
      path: '/aluno/$id'
      fullPath: '/aluno/$id'
      preLoaderRoute: typeof AlunoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cortex': {
      id: '/_authenticated/cortex'
      path: '/cortex'
      fullPath: '/cortex'
      preLoaderRoute: typeof AuthenticatedCortexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCortexRoute: typeof AuthenticatedCortexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCortexRoute: AuthenticatedCortexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlunosRoute: AlunosRoute,
  AuthRoute: AuthRoute,
  EntidadesRoute: EntidadesRoute,
  EscolaRoute: EscolaRoute,
  IntegracaoRoute: IntegracaoRoute,
  IntervencaoRoute: IntervencaoRoute,
  TurmasRoute: TurmasRoute,
  AlunoIdRoute: AlunoIdRoute,
  TurmaIdRoute: TurmaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
